[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/icon.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/resume.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline; filename=\"Hamza_Malik_Resume.pdf\""
